export const routesInfo = {
	Acela: { icon: "🚄", link: "acela" },
	Adirondack: { icon: "⛰️", link: "adirondack" },
	"Amtrak Cascades": { icon: "🌲", link: "cascades" },
	"Amtrak Hartford Line": { icon: "🚆", link: "amtrak-hartford-line" },
	"Auto Train": { icon: "🚗", link: "auto" },
	"Berkshire Flyer": { icon: "🌳", link: "berkshire-flyer" },
	"Blue Water": { icon: "💧", link: "michigan-services" },
	Borealis: { icon: "🌌", link: "borealis" },
	"California Zephyr": { icon: "🌄", link: "california-zephyr" },
	"Capitol Corridor": { icon: "🌉", link: "capitol-corridor" },
	"Capitol Limited": { icon: "🏛️", link: "capitol-limited" },
	Cardinal: { icon: "🐦", link: "cardinal" },
	"Carl Sandburg": { icon: "📖", link: "illinois-services" },
	Carolinian: { icon: "🐿️", link: "carolinian-piedmont" },
	"City Of New Orleans": { icon: "🎷", link: "city-of-new-orleans" },
	"Coast Starlight": { icon: "🌊", link: "coast-starlight" },
	"Connecting Bus": { icon: "🚌" },
	Crescent: { icon: "🌙", link: "crescent" },
	Downeaster: { icon: "🍂", link: "downeaster" },
	"Empire Builder": { icon: "🏔️", link: "empire-builder" },
	"Empire Service": { icon: "🗽", link: "empire-service" },
	"Ethan Allen Express": { icon: "🪓", link: "ethan-allen-express" },
	Floridian: { icon: "🌴", link: "floridian" },
	"Heartland Flyer": { icon: "🌽", link: "heartland-flyer" },
	"Hiawatha Service": { icon: "⛴️", link: "hiawatha" },
	Illini: { icon: "🏫", link: "illinois-services" },
	"Illinois Zephyr": { icon: "🌾", link: "illinois-services" },
	"Keystone Service": { icon: "🔑", link: "keystone-service" },
	"Lake Shore Limited": { icon: "🚢", link: "lake-shore-limited" },
	"Lincoln Service": {
		icon: "🎩",
		link: "lincoln-service-missouri-river-runner",
	},
	"Maple Leaf": { icon: "🍁", link: "maple-leaf" },
	"Missouri River Runner": {
		icon: "💦",
		link: "lincoln-service-missouri-river-runner",
	},
	"Northeast Regional": { icon: "🌆", link: "northeast-regional" },
	"Pacific Surfliner": { icon: "🏄‍♂️", link: "pacific-surfliner" },
	Palmetto: { icon: "🌿", link: "silver-service-palmetto" },
	Pennsylvanian: { icon: "⚙️", link: "pennsylvanian" },
	"Pere Marquette": { icon: "⛵", link: "michigan-services" },
	Piedmont: { icon: "🏞️", link: "carolinian-piedmont" },
	Saluki: { icon: "🐕", link: "illinois-services" },
	"San Joaquins": { icon: "🧺", link: "san-joaquins" },
	"Silver Meteor": { icon: "🌠", link: "silver-service-palmetto" },
	"Silver Meteor/Palmetto": { icon: "🌴", link: "silver-service-palmetto" },
	"Southwest Chief": { icon: "🌵", link: "southwest-chief" },
	"Sunset Limited": { icon: "🌇", link: "sunset-limited" },
	"Texas Eagle": { icon: "🦅", link: "texas-eagle" },
	"Valley Flyer": { icon: "🍇", link: "valley-flyer" },
	Vermonter: { icon: "🛷", link: "vermonter" },
	Wolverine: { icon: "🐺", link: "michigan-services" },
	"Mardi Gras Service": { icon: "🎭", link: "mardi-gras-service" }
};
